#!/usr/bin/env bash

yap() {
    echo "$@"
}

source "$HOME/.config/nyafish/fishrc" || (yap "WHERE IS MY FISHRC!!!"; exit 1)

audio() {
    case "$1" in
        "up")
        (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > "$HYPRFISH_WOBSOCK_PATH") || \
            (wpctl set-volume @DEFAULT_AUDIO_SINK@ "$HYPRFISH_AUDIO_STEP"%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | \
            sed 's/[^0-9]//g' > "$HYPRFISH_WOBSOCK_PATH")
        ;;
        "down")
        (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > ~/.wobsock) || \
            (wpctl set-volume @DEFAULT_AUDIO_SINK@ "$HYPRFISH_AUDIO_STEP"%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | \
            sed 's/[^0-9]//g' > "$HYPRFISH_WOBSOCK_PATH")
        ;;
        "togglemute")
        # shellcheck disable=SC2015
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && \
            (wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo 0 > "$HYPRFISH_WOBSOCK_PATH") || \
            wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > "$HYPRFISH_WOBSOCK_PATH"
        ;;
        *)
        yap "audio: up|down|togglemute"
        exit 1
        ;;
    esac
}

brightness() {
    case "$1" in
        "up")
        brightnessctl set "$HYPRFISH_BRIGHTNESS_STEP"%+ | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > ~/.wobsock
        ;;
        "down")
        brightnessctl set "$HYPRFISH_BRIGHTNESS_STEP"%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > ~/.wobsock
        ;;
        *)
        yap "brightness: up|down"
        exit 1
        ;;
    esac
}

screenshot() {
	mkdir -p $HYPRFISH_SCREENSHOT_DIR
	
    case "$1" in
        full)
        screenshot_location="$HYPRFISH_SCREENSHOT_DIR/$(date +'%y%m%d-%H%M%S-grim.png')"
        
        grim "$screenshot_location"
        wl-copy < "$screenshot_location"
        notify-send "Screenshot" "$screenshot_location"
        ;;
        partial)
        screenshot_location="$HYPRFISH_SCREENSHOT_DIR/$(date +'%y%m%d-%H%M%S-grim.png')"

        slurp -b 1b142eaa -w 0 | grim -g - - >> "$screenshot_location"
        wl-copy < "$screenshot_location"
        notify-send "Partial Screenshot" "$screenshot_location"
        ;;
        *)
        yap "screenshot: full|partial"
        exit 1
        ;;
    esac
}

new_workspace() {
    last_workspace="0"
    
    for id in $(hyprctl workspaces -j | jq .[].id); do
        if [[ $id -ge $last_workspace ]]; then
            last_workspace=$id
        fi
    done
    
    workspace_to_create=$((last_workspace + 1))
    
    if [[ $workspace_to_create -gt $HYPRFISH_MAX_WORKSPACE ]]; then
        notify-send "Error" "Can't have workspace more than $HYPRFISH_MAX_WORKSPACE."
        exit 1
    fi
    
    hyprctl dispatch workspace $workspace_to_create
}

launcher() {
	wofi --show drun --conf ~/.config/wofi/wofi.conf --style ~/.config/wofi/styles.css
}

keyboard() {
    wvkbd_pids="$(pidof wvkbd-mobintl)"

    if [[ "$wvkbd_pids" == "" ]]; then
        wvkbd-mobintl -O -L "$HYPRFISH_KEYBOARD_HEIGHT" \
            -l simple,special  --landscape-layers simple,special \
            -R 0 --bg 0e0e0e --fg 404040 --fg-sp 242424 \
            --press ffffff --press-sp ffffff \
            --text ffffff --text-sp e624af \
            --fn "Jetbrains Mono Nerd Font 20" | clickclack -f ~/.config/hyprfish/osk-sfx/keypress.wav &
    else
        # shellcheck disable=SC2086
        kill $wvkbd_pids
    fi
}

workspace() {
    current_workspace="$(hyprctl activeworkspace -j | jq .id)"

    case "$1" in
        up)
        if [[ "$current_workspace" -lt "$HYPRFISH_MAX_WORKSPACE" ]]; then
            hyprctl dispatch workspace $((current_workspace + 1))
        fi
        ;;
        down)
        if [[ "$current_workspace" -gt 1 ]]; then
            hyprctl dispatch workspace $((current_workspace - 1))
        fi
        ;;
        *)
        yap "workspace: up|down"
        ;;
    esac
}

movetoworkspace() {
    current_workspace="$(hyprctl activeworkspace -j | jq .id)"

    case "$1" in
        up)
        if [[ "$current_workspace" -lt "$HYPRFISH_MAX_WORKSPACE" ]]; then
            hyprctl dispatch movetoworkspace $((current_workspace + 1))
        fi
        ;;
        down)
        if [[ "$current_workspace" -gt 1 ]]; then
            hyprctl dispatch movetoworkspace $((current_workspace - 1))
        fi
        ;;
        *)
        yap "movetoworkspace: up|down"
        ;;
    esac
}

logout() {
    pkill steam
    while pidof steam; do
        sleep 1
    done
    #pkill dbus-daemon
    #while pidof dbus-daemon; do
    #    sleep 1
    #done
    sleep 1
    hyprctl dispatch exit
}

case $1 in
    audio|brightness|screenshot|launcher|new_workspace|keyboard|workspace|movetoworkspace|logout)
    # shellcheck disable=SC2068
    "$1" ${@:2}
    ;;
    *)
    yap "$0: audio|brightness|launcher|screenshot|new_workspace|keyboard|workspace|movetoworkspace|logout"
    exit 1
    ;;
esac
